### ISSUE TITLE
Unlicense?

### ISSUE THREAD

**Issue by Hexstream** [Jach/cl-ses4#1]
I was just wondering if you were aware of the [Unlicense](https://unlicense.org/), probably the best public domain license.

I've been using it for [all my open-source projects](https://www.hexstreamsoft.com/) (except 1) since forever and it's really great...

**Comment by Jach** [comment]
I think I've come across it before, but I don't remember why I rejected it. Looking now I like its boilerplate more than my clumsy PD+optional CC0 for impoverished jurisdictions wording, and github has a widget for it too. Thanks, you've convinced me to use it going forward. :)

**Comment by Hexstream** [comment]
Awesome!! I rarely convince anyone of anything, heh.
